name: START RUN

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Index Script
      run: |
        chmod +x w8x64.sh
        ./w8x64.sh
